name: flume_example
description: Example application using the Flume design system.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flume:
    path: ../
  cupertino_icons: ^1.0.5
  shake: ^2.2.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: FlumeIcons
      fonts:
        - asset: packages/flume/fonts/FlumeIcons.ttf

    - family: Sora
      fonts:
        - asset: packages/flume/fonts/Sora.ttf # variable font

    - family: Mulish
      fonts:
        - asset: packages/flume/fonts/MulishMedium.ttf
          weight: 500

  assets:
    - assets/
    - assets/icon/
