name: flume_example
description: Example application using the Flume design system.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flume:
    path: ../
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: FlumeIcons
      fonts:
        - asset: packages/flume/fonts/FlumeIcons.ttf

    - family: Montserrat
      fonts:
        - asset: packages/flume/fonts/MontserratMedium.ttf
          weight: 500
        - asset: packages/flume/fonts/MontserratSemiBold.ttf
          weight: 600

    - family: Mulish
      fonts:
        - asset: packages/flume/fonts/MulishMedium.ttf
          weight: 500

  assets:
    - assets/
    - assets/icon/
