name: flume
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/gameflow-tv/flume_flutter

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  figma: ^3.6.0
  progress_bar: ^1.0.0
  http: ^0.13.5
  test: ^1.21.4

flutter:
  assets:
    - lib/licenses/

  fonts:
    - family: FlumeIcons
      fonts:
        - asset: lib/fonts/FlumeIcons.ttf

    - family: Montserrat
      fonts:
        - asset: lib/fonts/MontserratMedium.ttf
          weight: 500
        - asset: lib/fonts/MontserratSemiBold.ttf
          weight: 600

    - family: Mulish
      fonts:
        - asset: lib/fonts/MulishMedium.ttf
          weight: 500
