name: flume
description: Implementation of the Flume design system and components for Flutter.
version: 0.0.0
homepage: https://github.com/gameflow-tv/flume_mobile

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  equatable: ^2.0.5
  provider: ^6.0.5
  shimmer: ^2.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  figma: ^5.0.3
  progress_bar: ^1.0.0
  http: ^0.13.5
  test: ">1.24.0<1.24.2"
  args: ^2.4.0

flutter:
  assets:
    - lib/licenses/

  fonts:
    - family: FlumeIcons
      fonts:
        - asset: lib/fonts/FlumeIcons.ttf

    - family: Montserrat
      fonts:
        - asset: lib/fonts/MontserratMedium.ttf
          weight: 500
        - asset: lib/fonts/MontserratSemiBold.ttf
          weight: 600

    - family: Mulish
      fonts:
        - asset: lib/fonts/MulishMedium.ttf
          weight: 500

screenshots:
  - description: "Illustration of the Flume design system."
    path: assets/pub/thumbnail.png

  - description: "Illustration of the Ambiance system."
    path: assets/docs/elevation_example.png
