name: flume
description: Implementation of the Flume design system and components for Flutter.
version: 0.0.0
homepage: https://github.com/gameflow-tv/flume_mobile
documentation: https://flume.gameflow.dev
issue_tracker: https://github.com/gameflow-tv/flume_mobile/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  equatable: ^2.0.5
  provider: ^6.0.5
  shimmer: ^3.0.0
  intl: ^0.18.1
  flutter_staggered_animations: ^1.1.1
  flutter_cache_manager: ^3.3.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  figma: ^7.0.0
  progress_bar: ^1.0.0
  http: ^1.1.0
  test: ^1.24.9
  args: ^2.4.2
  xml: ^6.4.2

dependency_overrides:
  collection: ^1.17.2
  http: ^1.0.0

flutter:
  assets:
    - lib/licenses/

  fonts:
    - family: FlumeIcons
      fonts:
        - asset: lib/fonts/FlumeIcons.ttf

screenshots:
  - description: "Illustration of the Flume design system."
    path: www/static/img/hero.png

  - description: "Illustration of the Ambiance system."
    path: assets/docs/elevation_example.png
