name: Pull Request

on:
  pull_request:

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: master
          cache: true
      - run: flutter pub get
      - run: flutter test --coverage
